# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
r:
  - oldrel
  - release
  - devel
matrix:
  allow_failures:
    - r: devel
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - knitr
  - rmarkdown
  - pkgKitten
addons:
  apt:
    sources:
    - sourceline: 'ppa:keithw/glfw3'
    packages:
    - libglfw3
before_install:
  - wget http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1_Linux_x86_64.sh
  - sudo sh ArrayFire-v3.5.1_Linux_x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
  - rm ArrayFire-v3.5.1_Linux_x86_64.sh
after_success:
  - Rscript -e 'covr::codecov()'
