# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
addons:
  apt:
    packages:
      - libglfw3
install:
  - wget http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1_Linux_x86_64.sh
  - sudo sh ArrayFire-v3.5.1_Linux_x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
