# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
latex: false
fortran: false

matrix:
  include:
  - r: oldrel
  - r: release
    r_packages:
    - covr
    - devtools
    - pkgdown
    r_github_packages:
    - metrumresearchgroup/covrpage
    after_success:
    - Rscript -e "covr::codecov()"
    deploy:
      provider: script
      script: Rscript -e 'devtools::install(); covrpage::covrpage_ci(); pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
  - r: release
    os: osx

notifications:
  email:
    on_success: change
    on_failure: change
addons:
  apt:
    sources:
    - sourceline: 'ppa:keithw/glfw3'
    packages:
    - libglfw3
brew_packages:
  - fontconfig
  - glfw
before_install:
  - test "$TRAVIS_OS_NAME" == "linux" && sh .travis/before_install_linux.sh || true
  - test "$TRAVIS_OS_NAME" == "osx" && sh .travis/before_install_osx.sh || true
script:
  - test "$TRAVIS_OS_NAME" == "linux" && export LD_PRELOAD="/opt/arrayfire/lib/libmkl_core.so:/opt/arrayfire/lib/libtbb.so.2:/opt/arrayfire/lib/libmkl_tbb_thread.so"
  - export PKG_TARBALL=RcppArrayFire_$(grep '^Version:' DESCRIPTION | grep -o '[0-9\.]*').tar.gz
  - R CMD build --no-manual .
  - R CMD check --no-manual $PKG_TARBALL
