# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
matrix:
  allow_failures:
    - r: devel
  exclude:
  - r: oldrel
    os: osx
  - r: devel
    os: osx
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - knitr
  - rmarkdown
  - pkgKitten
addons:
  apt:
    sources:
    - sourceline: 'ppa:keithw/glfw3'
    packages:
    - libglfw3
before_install:
  - test "$TRAVIS_OS_NAME" == "linux" && sh .travis/before_install_linux.sh
  - test "$TRAVIS_OS_NAME" == "osx" && sh .travis/before_install_osx.sh
after_success:
  - Rscript -e 'covr::codecov()'
