# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
r:
#  - oldrel
  - release
#  - devel
install:
  - sudo apt-add-repository ppa:keithw/glfw3
  - sudo apt-get update
  - sudo apt-get install glfw3
  - wget http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1_Linux_x86_64.sh
  - sudo sh ArrayFire-v3.5.1_Linux_x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
